export const FECTH_CALENDER_EVENT = 'FECTH_CALENDER_EVENT';
export const FECTH_CALENDER_EVENT_SUCCESS = 'FECTH_CALENDER_EVENT_SUCCESS';
export const FECTH_CALENDER_EVENT_ERROR = 'FECTH_CALENDER_EVENT_ERROR';